# -*- mode: shell-script -*-
# (c) Copyright [2021] Micro Focus or one of its affiliates.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

# Base operating system
ARG os_version="18.04"

FROM ubuntu:${os_version} as builder

# useful to keep dpkg from prompting us for information
ENV DEBIAN_FRONTEND noninteractive
ENV TERM 1

# required for Ubuntu because Vertica installer insists on it
ENV SHELL "/bin/bash"

# Create DB user and group in OS. Fix their ID, so they match in the following stage
RUN set -x \
 && apt-get update -y \
 && apt-get upgrade --no-install-recommends -y \
 && apt-get install --no-install-recommends -yqq \
            autotools-dev \
            bash \
            binutils \
            build-essential \
            cmake \
            curl \
            doxygen \
            expat \
            flex \
            g++ \
            gcc \
            gdb \
            gettext \
            git \
            libc-dev \
            libtool \
            locales \
            make \
            nasm \
            procps \
            sudo \
            tar \
            vim \
 && chsh -s /bin/bash root 

LABEL image_name="vertica_wasm_udx_development"
LABEL maintainer="SDK Team"
