# -*- mode: shell-script -*-
# (c) Copyright [2021-2023] Open Text.
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
############################################################################

# Base operating system
ARG os_version
ARG os_image

FROM ${os_image}:${os_version}

# useful to keep dpkg from prompting us for information
ENV DEBIAN_FRONTEND noninteractive
ENV TERM 1

ENV VERTICA_OPT_DIR="/opt/vertica"

ARG vertica_db_user="dbadmin"
ARG vertica_db_group="verticadba"
ARG dbadmin_gid=1000
ARG dbadmin_id=1000

ENV VERTICA_HOME_DIR="/home/$vertica_db_user"

# name of .deb file
ARG DEB
ARG vertica_version

COPY $DEB /tmp/$DEB

# required for Ubuntu because Vertica installer insists on it
ENV SHELL "/bin/bash"

# Install prerequisites and development tools
RUN set -x \
 && apt-get update -y \
 && apt-get upgrade --no-install-recommends -y \
 && apt-get install -y \
            # Packages needed to build C++ UDxes
            autotools-dev \
            bash \
            binutils \
            build-essential \
            ca-certificates \
            cmake \
            curl \
            dialog \
            doxygen \
            expat \
            flex \
            g++ \
            gcc \
            gdb \
            gettext \
            less \
            libacl1-dev \
            libboost-all-dev \
            libbz2-dev \
            libc-dev \
            libcurl4-openssl-dev \
            libgomp1 \
            libicu-dev \
            libkeyutils1 \
            libreadline-dev \
            libtool \
            locales \
            make \
            nasm \
            openssh-server \
            openssl \
            procps \
            sudo \
            tar \
            vim \
 && chsh -s /bin/bash root \
 # Fix locales
 && /bin/echo "en_US ISO-8859-1" > /etc/locale.gen \
 && /bin/echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
 && /usr/sbin/locale-gen \
 # Create development user
 && /usr/sbin/groupadd -r -g $dbadmin_gid $vertica_db_group \
 && /usr/sbin/useradd \
            -r \
            -m \
            -s /bin/bash \
            -g $vertica_db_group \
            -u $dbadmin_id \
            $vertica_db_user

# Install Vertica package (for SDK headers and libraries only)
RUN dpkg -i /tmp/${DEB} && rm -f /tmp/${DEB}

RUN chown -R $vertica_db_user:$vertica_db_group $VERTICA_OPT_DIR \
    && chown -R $vertica_db_user:$vertica_db_group ${VERTICA_HOME_DIR} \
    && chmod 755 ${VERTICA_HOME_DIR} \
    # Allow passwordless sudo access from any user
    && echo "ALL ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers

ADD ./env_setup/vertica_env.sh /etc/profile.d/
COPY entrypoint.sh /opt/vertica/bin/entrypoint.sh

# Overwrite path in /etc/environment for non-root users
RUN echo PATH="/opt/vertica/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" > /etc/environment
ENV PATH="/opt/vertica/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" 

# This disables a warning message when the group is unknown
RUN touch /.sudo_as_admin_successful

# Run as development user
USER $vertica_db_user

WORKDIR ${VERTICA_HOME_DIR}

ENTRYPOINT  [ "/opt/vertica/bin/entrypoint.sh" ]

LABEL image_name="vertica_udx_development"
LABEL os_family="$CONTAINER_OS"
LABEL os_version="$CONTAINER_OS_VERSION"
LABEL vertica_version="$VERTICA_VERSION"
LABEL maintainer="K8 Team"
